version: "3.9"
services:
  db:
    image: postgres:14-alpine
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bookstore_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
